// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/about.tsx";
import * as $4 from "./routes/api/cart/index.ts";
import * as $5 from "./routes/api/cart/pay.ts";
import * as $6 from "./routes/api/inventory/[id].ts";
import * as $7 from "./routes/cart.tsx";
import * as $8 from "./routes/category/[slug].tsx";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/login.tsx";
import * as $11 from "./routes/products/[slug].tsx";
import * as $12 from "./routes/products/index.tsx";
import * as $13 from "./routes/profile.tsx";
import * as $14 from "./routes/register.tsx";
import * as $15 from "./routes/search.tsx";
import * as $$0 from "./islands/BuyButton.tsx";
import * as $$1 from "./islands/CartProduct.tsx";
import * as $$2 from "./islands/Filters.tsx";
import * as $$3 from "./islands/Inventory.tsx";
import * as $$4 from "./islands/Navigation.tsx";
import * as $$5 from "./islands/SearchForm.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/about.tsx": $3,
    "./routes/api/cart/index.ts": $4,
    "./routes/api/cart/pay.ts": $5,
    "./routes/api/inventory/[id].ts": $6,
    "./routes/cart.tsx": $7,
    "./routes/category/[slug].tsx": $8,
    "./routes/index.tsx": $9,
    "./routes/login.tsx": $10,
    "./routes/products/[slug].tsx": $11,
    "./routes/products/index.tsx": $12,
    "./routes/profile.tsx": $13,
    "./routes/register.tsx": $14,
    "./routes/search.tsx": $15,
  },
  islands: {
    "./islands/BuyButton.tsx": $$0,
    "./islands/CartProduct.tsx": $$1,
    "./islands/Filters.tsx": $$2,
    "./islands/Inventory.tsx": $$3,
    "./islands/Navigation.tsx": $$4,
    "./islands/SearchForm.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
